language: haxe

cache:
  directories:
    - $HOME/.m2
    - $HOME/flex_sdk
rvm:
- 2.2.3

addons:
  apt:
    packages:
    - protobuf-compiler

before_install:
  - gem update --system
  - gem install bundler
  - bundle install
  - wget http://download.macromedia.com/pub/flex/sdk/flex_sdk_3.6.zip
  - unzip -d $HOME/flex_sdk flex_sdk_3.6.zip



before_script:
  - sudo apt-get update                                # run update before installing anything
  - sudo apt-get install python-software-properties -y # for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y      # add the ubuntu ppa that contains haxe
  - sudo apt-get update                                # pull info from ppa
  - sudo apt-get install haxe -y                       # install haxe (and neko)
  - sudo apt-get install gcc-multilib g++-multilib -y  # VM is 64bit but hxcpp builds 32bit
  - mkdir ~/haxelib                                    # create a folder for installing haxelib
  - haxelib setup ~/haxelib
  - haxelib install hxcpp                              # install hxcpp to test C++ target
  - mkdir bin                                          # create an output folder if needed


install:
  - haxelib install haxelib-run
  - git clone --branch v2.6.1 --depth 1 https://github.com/google/protobuf.git
  - |
    echo '
    PROTOBUF_VERSION=2.6.1
    PROTOBUF_DIR=protobuf
    ifeq ($(OS), Windows_NT)
    BAT=.bat
    EXE=.exe
    PATH_SEPARATOR=;
    else
    PATH_SEPARATOR=:
    endif
    COMPC=$HOME/flex_sdk/bin/compc$(BAT)
    MXMLC=$HOME/flex_sdk/bin/mxmlc$(BAT)
    ASDOC=$HOME/flex_sdk/bin/asdoc$(BAT)
    FDB=$HOME/flex_sdk/bin/fdb$(BAT)
    MVN=mvn
    JAVAC=javac
    JAR=jar
    HAXE=haxe
    ' > config.mk
  - make protobuf/src/protoc

script:
  - make

